# Generated by Django 5.1 on 2024-10-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0002_createitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createitem',
            name='photo',
        ),
    ]
