# Generated by Django 5.1 on 2024-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0003_remove_createitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='createitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
